### ISSUE TITLE
Delete comments in html

### ISSUE THREAD

**Issue by jema28** [fack2/toDoApp#17]
Please delete unused code in html 💄 

https://github.com/fack2/toDoApp/blob/3766fb03ea2fdd9afe766cb060ed67b921dc26e3/index.html#L42-L47

https://github.com/fack2/toDoApp/blob/3766fb03ea2fdd9afe766cb060ed67b921dc26e3/index.html#L28

**Comment by enasmtour** [comment]
done @jema28
