### ISSUE TITLE
Avoid for loops

### ISSUE THREAD

**Issue by jema28** [fack2/toDoApp#19]
Can you refactor these to avoid for loops? There are cleaner ways of writing this 🐼 

https://github.com/fack2/toDoApp/blob/3766fb03ea2fdd9afe766cb060ed67b921dc26e3/logic.js#L39-L45

https://github.com/fack2/toDoApp/blob/3766fb03ea2fdd9afe766cb060ed67b921dc26e3/logic.js#L63-L67

**Comment by enasmtour** [comment]
Done
