### ISSUE TITLE
Avoid innerHTML

### ISSUE THREAD

**Issue by jema28** [fack2/toDoApp#21]
You should try avoiding using innerHTML as it can cause security risks.

> The idea behind an XSS attack with innerHTML is that malicious code would get injected into your site and then execute. This is possible because innerHTML renders complete markup and not just text.

-- https://gomakethings.com/a-safer-alternative-to-innerhtml-with-vanilla-js/

https://github.com/fack2/toDoApp/blob/3766fb03ea2fdd9afe766cb060ed67b921dc26e3/dom.js#L23

**Comment by enasmtour** [comment]
DONE @jema28
