### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by jema28** [fack2/toDoApp#23]
1. This variable name could be more semantic e.g. completedToDos.
https://github.com/fack2/toDoApp/blob/3766fb03ea2fdd9afe766cb060ed67b921dc26e3/dom.js#L7
2. Change "div1" to something more useful, maybe `sort-buttons`. https://github.com/fack2/toDoApp/blob/3766fb03ea2fdd9afe766cb060ed67b921dc26e3/index.html#L30

**Comment by enasmtour** [comment]
DONE @jema28
